<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by hotellidiilid</title>
</head>
<body>
    <h1>Booking Cancellation</h1>
    
    Reference : <p>{{ $cancellation["reference"] }}</p>
    Cancellation Reference : <p>{{ $cancellation["cancellationReference"] }}</p>
    Client Reference<p>{{ $cancellation["clientReference"] }}</p>
    Created On: <p>{{ $cancellation["creationDate"] }}</p>
    Status : <p>{{ $cancellation["status"] }}</p>
    CreatedBy : <p>{{ $cancellation["creationUser"] }}</p>
    Holder Name : <p>{{ $cancellation["holder"]}}</p>
</body>
</html>